### ISSUE TITLE
Colorado: Sudden, unexplained "gunshot heard" alerts

### ISSUE THREAD

**Issue by wachsmuth** [edisleado/Hitman-Bug-Tracker#102]
This has happened twice now. Suddenly all the guards get alerted due to 'gunshot heard'. This happened even at times when no one was suspicious of me and I had not fired any shots at all.

In both cases, I was near the barn or the shooting range, while someone at the shooting range or the Gustavo Torres-assassination training area was shooting. Also in both cases I was wearing a disguise that wasn't allowed in the barn or the shooting range. I suspect that the guards 'hear' some of the shots from the shooting range, and somehow associate those with shots that would actually be suspicious.

**Comment by gremmie** [comment]
I had this happen to me as well. In my case I was in the house.

**Comment by wachsmuth** [comment]
I haven't heard of these in a while. It's possible they have been fixed. It's not the easiest bug to reproduce, but I haven't had them at all while playing Colorado lately, and they used to be more common than that for sure.

**Comment by wachsmuth** [comment]
According to the November update changelog this has been fixed. It's a difficult bug to reproduce, so I'll close it and assume that it did indeed get fixed - we can always reopen the issue if the bug turns up again.
