### ISSUE TITLE
Poison and Emetic syringes have different perspectives in loadout

### ISSUE THREAD

**Issue by leet-it-b** [edisleado/Hitman-Bug-Tracker#103]
![20160929153251_1](https://cloud.githubusercontent.com/assets/20925661/18954233/a9473e12-865a-11e6-85df-3ccc2b315ef9.jpg)

**Comment by HMBM47** [comment]
Fixed.
They both have the same perspective as the Modern Emetic Syringe in the picture above.

**Comment by leet-it-b** [comment]
Yeah. Closed
