### ISSUE TITLE
Colorado: If overdose administered to hostage after he has been killed, he still moans

### ISSUE THREAD

**Issue by wachsmuth** [edisleado/Hitman-Bug-Tracker#109]
It's possible to kill the hostage with the Wicker Man easter egg. If you attempt to give him an overdose after he's dead, he moans anyway, despite the fact that he is dead.

**Comment by leet-it-b** [comment]
He's still moans, when you give him overdose but just one time in the beginning, not permanently. 
IDK were there some fixes or not.

**Comment by wachsmuth** [comment]
Yeah, that's the original behaviour. Apparently no changes then.

**Comment by wachsmuth** [comment]
Fixed
