### ISSUE TITLE
Weird trespassing boundary on observatory roof in World of Tomorrow

### ISSUE THREAD

**Issue by wachsmuth** [edisleado/Hitman-Bug-Tracker#110]
I assume the entire roof is meant to be trespassing area. However, there's a small area of the roof that's not. Compare these two images:

![20161002013119_1](https://cloud.githubusercontent.com/assets/9452728/19017622/2dca6348-8841-11e6-8d84-c5df40b27b54.jpg)
![20161002013123_1](https://cloud.githubusercontent.com/assets/9452728/19017623/307ed81c-8841-11e6-9b0d-6fafe7208e35.jpg)

**Comment by leet-it-b** [comment]
> Fixed inconsistent trespassing boundaries in Sapienza
https://hitman.com/en-us/updates/november-update-release-notes
![20161128191709_1](https://cloud.githubusercontent.com/assets/20925661/20676008/59ca029c-b59f-11e6-9f0a-12ae2c9b4c15.jpg)
