### ISSUE TITLE
Colorado: Door in Sean Rose's room can not be opened by Rose's Room Key

### ISSUE THREAD

**Issue by wachsmuth** [edisleado/Hitman-Bug-Tracker#111]
The door between Sean Rose's bathroom and his bedroom gets locked when Rose goes into the bathroom. Then, bizarrely the key for Sean Rose's room doesn't work, it can only be opened by a crowbar or lockpick (see picture). This _could_ be intentional, but I doubt it.

![20161002202809_1](https://cloud.githubusercontent.com/assets/9452728/19023898/810a4aba-88f9-11e6-9075-d44fb6e57fde.jpg)

**Comment by gremmie** [comment]
I noticed that too. You can also enter the bathroom from the hallway without a key when Rose is not in the bathroom. This made me believe that Rose locks the bathroom doors when he goes in there and there is no key for it. But it could also very well be a bug.

**Comment by leet-it-b** [comment]
> Fixed an issue where a door in Sean Rose's room could not be opened by Rose's Room Key
https://hitman.com/en-us/updates/november-update-release-notes
