### ISSUE TITLE
Bangkok - Exterminator Disguise has slight clipping on the back of 47's (or NPC's) upper arms

### ISSUE THREAD

**Issue by HMBM47** [edisleado/Hitman-Bug-Tracker#116]
![exterminatorclipping](https://cloud.githubusercontent.com/assets/20890580/19407559/c150a8ca-925a-11e6-9911-ad3875e92c42.jpg)

**Comment by leet-it-b** [comment]
Fixed?
![20161128185616_1](https://cloud.githubusercontent.com/assets/20925661/20675275/c74d8990-b59c-11e6-89f4-899a86a3a87c.jpg)
