### ISSUE TITLE
A Gilded Cage opportunity 'Open Sesame' does not complete

### ISSUE THREAD

**Issue by wachsmuth** [edisleado/Hitman-Bug-Tracker#134]
The headmaster key opportunity. If you track it, you will fail as soon as you enter the school. I have seen no way at all to complete it. It seems to be impossible to get the achievement for completing all opportunities in A Gilded Cage right now.

**Comment by leet-it-b** [comment]
Fixed in November update?
https://hitman.com/en-us/updates/november-update-release-notes

**Comment by wachsmuth** [comment]
Fixed
