### ISSUE TITLE
Open Sesame Bug (PC) - Episode 3 - Marrakesh

### ISSUE THREAD

**Issue by MelvinWhite** [edisleado/Hitman-Bug-Tracker#144]
Opportunity always fails for whatever reason. Unable to unlock the "Tourist Attractions" achievement/trophy because of this.
[https://www.youtube.com/watch?v=QQBfk59eQcU](url)
If the link doesn't work simply copy QQBfk59eQcU into YouTube search.

**Comment by wachsmuth** [comment]
Duplicate of #134 , these should be merged.

**Comment by leet-it-b** [comment]
Fixed in November update?
https://hitman.com/en-us/updates/november-update-release-notes

**Comment by wachsmuth** [comment]
It has indeed been fixed (just tested it). Time to close this issue :)
