### ISSUE TITLE
Trespassing Zone Glitch in Paris

### ISSUE THREAD

**Issue by jmdinbtr** [edisleado/Hitman-Bug-Tracker#146]
I noticed this zone layout glitch today while playing in Paris. In the basement/wine cellar in the hall by the security office, if you stand against the wall you are no longer trespassing. If you move back into the hall, you are trespassing. Anyone else see this? I'm on PC.

[Trespassing](http://imgur.com/TkKlSEs) and [not trespassing](http://imgur.com/5GLvLxn) images.

**Comment by leet-it-b** [comment]
Fixed
![20161128195407_1](https://cloud.githubusercontent.com/assets/20925661/20677581/8728dc36-b5a4-11e6-8b0e-92e2c6a82d58.jpg)

**Comment by jmdinbtr** [comment]
Awesome! My first report gets a fix. Thanks!

**Comment by leet-it-b** [comment]
Can you please close it to keep the tracker actual?
![4oxorwu](https://cloud.githubusercontent.com/assets/20925661/20680312/914cb2b8-b5af-11e6-9b3d-ee29ca1a0822.png)

**Comment by jmdinbtr** [comment]
Done!
