### ISSUE TITLE
Sapienza | Can't drag Silvio's body

### ISSUE THREAD

**Issue by LiteralMetaphorical** [edisleado/Hitman-Bug-Tracker#147]
After killing Silvio by smothering him with the pillow while dressed as the therapist, you can't drag his body as there is no "drag body" button prompt.

EDIT: I reported this to an IO employee that is a member at Hitmanforum, and he said this isn't a bug and is done intentionally since the guards are supposed to regard Silvio as "sleeping" when they see him on the couch. This, however, doesn't work properly and as soon as anyone sees Silvio on the couch, it counts as a body found and everyone goes on full alert.

I'm worried IO will ignore this issue entirely since the button prompt missing isn't a bug, but the guards realizing Silvio is dead IS a bug.

**Comment by HMBM47** [comment]
This has already been reported.
https://github.com/edisleado/Hitman-Bug-Tracker/issues/19
