### ISSUE TITLE
Remote explosives stuck inside tables

### ISSUE THREAD

**Issue by Spodey** [edisleado/Hitman-Bug-Tracker#15]
The explosives in both the tunnel and parking garage appear invisible, but can be collected/viewed in instinct. They become visible when picked up and retain their visibility if dropped again.

![c__data_users_defapps_appdata_internetexplorer_temp_saved images_screenshot-original 13](https://cloud.githubusercontent.com/assets/20890101/17489000/daaf9d90-5d93-11e6-8fe2-5629d803f8e5.png)

![c__data_users_defapps_appdata_internetexplorer_temp_saved images_screenshot-original 14](https://cloud.githubusercontent.com/assets/20890101/17489061/19cf222a-5d94-11e6-969c-00b8fd344f2d.png)

**Comment by Spodey** [comment]
I've noticed this issue also occurs with the remote explosive in the attic in Paris.

**Comment by edisleado** [comment]
Can you provide more screenshots of this issue in the Paris level? We can make this issue a global one.

**Comment by Spodey** [comment]
In fact, it seems that the explosives aren't invisible, but stuck in the table. In Paris, only part of the explosive is in the table, and the rest sticks out, whereas in Marrakesh, the mines are completely in the table.

I can get screenshots in a few minutes demonstrating this.

**Comment by Spodey** [comment]
![c__data_users_defapps_appdata_internetexplorer_temp_saved images_screenshot-original 17](https://cloud.githubusercontent.com/assets/20890101/17535175/f2f1bbe4-5e84-11e6-8262-228285b97a03.png)

**Comment by HMBM47** [comment]
Fixed in both locations.
![fixedmines01](https://cloud.githubusercontent.com/assets/20890580/18945908/6a9c7ec6-85e1-11e6-81e1-07e1e561ce05.jpg)
![fixedmines02](https://cloud.githubusercontent.com/assets/20890580/18945909/6ab60b20-85e1-11e6-8454-db0736c2403a.jpg)
