### ISSUE TITLE
Clothes rustling sound for certain disguises is really loud

### ISSUE THREAD

**Issue by HMBM47** [edisleado/Hitman-Bug-Tracker#156]
This seem to effect the disguises with lots of fabric such as the Priest disguise in Sapienza, the kimonos in Hokkaido, and the Hotel Staff disguise in Bangkok.
I would imagine there are more than the ones mentioned.

**Comment by leet-it-b** [comment]
Cook\Kitchen assistant too.
The idea is fine, but the volume should be reduced twice at least.

**Comment by edisleado** [comment]
I noticed it especially so with the Chef disguise in Sapienza. The rustling sound is loud and sometimes even carries on after 47 stops moving. I also can't resist posting the following video. Not gameplay, but it is very relevant: https://www.youtube.com/watch?v=7fr5ByQo5TI

**Comment by leet-it-b** [comment]
Tweaked in "december path"?
https://www.youtube.com/watch?v=H5MyM72VE6I

**Comment by HMBM47** [comment]
Sounds like it's been fixed!  👍
