### ISSUE TITLE
'w/gloves' Elusive Target suits not unlocking when they should be

### ISSUE THREAD

**Issue by insanekw** [edisleado/Hitman-Bug-Tracker#164]
Only found out just now the pre-reqs for getting these suits and then realised I should probably have a few more of them. Anyone had anything like this? Tried looking but nothing in relation to the 'w/gloves' suits specifically, just the Terminus one that was apparently fixed in some update in November.

EDIT: The Paris and Marrakesh suits w/gloves unlocked fine. 

![1](https://cloud.githubusercontent.com/assets/24385312/20880437/3fdf1c18-bb2c-11e6-87e7-80b026ce3d4f.jpg)
![2](https://cloud.githubusercontent.com/assets/24385312/20880438/3fe298a2-bb2c-11e6-96bf-45478ed56d1a.jpg)
![3](https://cloud.githubusercontent.com/assets/24385312/20880439/3fe74794-bb2c-11e6-9ae6-324865985cf0.jpg)
![4](https://cloud.githubusercontent.com/assets/24385312/20880441/3fecb2a6-bb2c-11e6-9947-8e116605e3ac.jpg)
![5](https://cloud.githubusercontent.com/assets/24385312/20880440/3fec3cfe-bb2c-11e6-8b26-e242beb6ae86.jpg)

**Comment by leet-it-b** [comment]
>It's equally important to note that the new rewards system comes into effect starting with ET 14, meaning that **you cannot retroactively unlock suits based on previous ET's**.

https://hitman.com/news/elusive-target-14

**Comment by insanekw** [comment]
Thanks for sorting that out for me. Didn't realise they were a recent addition.
