### ISSUE TITLE
Suits - Missing belt / see-through waist area

### ISSUE THREAD

**Issue by Jir2607** [edisleado/Hitman-Bug-Tracker#20]
The Absolution Suit unlock is missing it's belt. Already mentioned numerous times but still :)

**Comment by edisleado** [comment]
Definitely noticeable whenever you're crouching or climbing through windows. Anyways, IO has acknowledged the problem in their last gameplay stream so hopefully we can mark this issue as fixed soon!

**Comment by edisleado** [comment]
It's look like this issue applies to others suits too. The 2016 Signature Suit also appears to be missing it's belt area.

Video footage courtesy of Jjoa74:
http://www.hitmanforum.com/t/bug-report-thread/5297/1596?u=edisleado

**Comment by leet-it-b** [comment]
Belt fixed
![20160816234423_1](https://cloud.githubusercontent.com/assets/20925661/17715183/b9b27594-640b-11e6-90d5-3c39e34b0329.jpg)

![20160816234623_1](https://cloud.githubusercontent.com/assets/20925661/17715191/bf575370-640b-11e6-9a27-c5c845ccb8f3.jpg)
