### ISSUE TITLE
Camera system operates on global basis, nerfing gameplay complexity

### ISSUE THREAD

**Issue by edisleado** [edisleado/Hitman-Bug-Tracker#3]
New camera system operates on global basis, greatly reducing gameplay complexity. For levels with multiple camera systems, such as Sapienza, players no longer need to worry about being spotted by cameras in certain areas and can simply continue getting spotted by more cameras in the level, as they now have convenient options in many locations to entirely disable the camera system and delete evidence.

For instance, being spotted by a Sapienza "town" camera is much less of an issue after the global camera system update. Instead of having to infiltrate the town clock tower and access the top floor office to disable the camera system there, players can simply opt to continue with the mission and use the camera system in the Biolab on their way out of the level. Previously, players would have had to access every one of the following areas to truly eliminate all evidence if they were spotted by the relevant camera systems: church basement, clock tower office, biolab, and mansion security room.

**Comment by wachsmuth** [comment]
It seems that this is indeed how it works in the Professional difficulty. Haven't tested it yet, but if it works as advertised this issue can be viewed as being fixed.

**Comment by wachsmuth** [comment]
This can be closed now with the introduction of the Professional difficulty. Just had a look at it and I think it adresses these issues basically by making the camera system much more complicated.
