### ISSUE TITLE
Escalations completed before the patch that put check marks on completed escalations, still don't have check marks

### ISSUE THREAD

**Issue by HMBM47** [edisleado/Hitman-Bug-Tracker#40]
Escalation was completed before patch.
![hitman 2016-08-09 11-03-00](https://cloud.githubusercontent.com/assets/20890580/17527714/526d8012-5e21-11e6-8419-33a1f0fe26a0.jpg)
Still no check mark.
![hitman 2016-08-09 11-03-24](https://cloud.githubusercontent.com/assets/20890580/17527720/59365aae-5e21-11e6-9939-d59271a041ea.jpg)

**Comment by edisleado** [comment]
Can you provide any screenshots?

**Comment by HMBM47** [comment]
Fixed.
All escalations finished before patch now have check marks.
