### ISSUE TITLE
Paris. No footsteps sounds on the top floor balcoly

### ISSUE THREAD

**Issue by leet-it-b** [edisleado/Hitman-Bug-Tracker#44]
Minor audio glitch
https://www.youtube.com/watch?v=qO3WTzo3brU

**Comment by edisleado** [comment]
Hi Leet,

There is already a thread for this:
https://github.com/edisleado/Hitman-Bug-Tracker/issues/22

Can you post your video in that thread as a comment? I will mark this thread as a duplicate and will close it after you do so.

**Comment by leet-it-b** [comment]
Done

**Comment by leet-it-b** [comment]
Also, I searched by "Audio" tag before posting this, and #22 has no audio tag on it :)

**Comment by edisleado** [comment]
Sorry, I've added the audio tag now. Thanks for the heads up! I'll mark this as a duplicate and close it now.
