### ISSUE TITLE
Bugged "sabotage" option on mechanical teeth

### ISSUE THREAD

**Issue by leet-it-b** [edisleado/Hitman-Bug-Tracker#46]
Sometimes it's not available until you get the right angle.
https://www.youtube.com/watch?v=3KYrwaNUQyA

**Comment by HMBM47** [comment]
You should probably test this out for yourself, since I didn't check this out when you reported it.
But playing it right now, just as long as 47 is in range and the box is in view, there doesn't seem to be an issue.

**Comment by leet-it-b** [comment]
Fixed, thank you!
