### ISSUE TITLE
Sapienza's balcony — illogical trespassing area?

### ISSUE THREAD

**Issue by leet-it-b** [edisleado/Hitman-Bug-Tracker#48]
It's suggestion, not a bug. 
![untitled-1](https://cloud.githubusercontent.com/assets/20925661/17576309/da59b050-5f79-11e6-953c-5b14163960f7.jpg)
I mean, there is nothing spectacular in this area, it's just a balcony between two appartments. Anybody can be here. Who cares about man in the suit on the balcony?
![20160811021852_1](https://cloud.githubusercontent.com/assets/20925661/17576315/e824ce72-5f79-11e6-8a09-2b075dcf0b41.jpg)
 I understand, that you can reach this balcony only through these locked appartments, but balcony itself not a part of them and peoples on the streets can't know about your trespassing.  And  it's kinda weird when NPC from the street see 47 on this balcony and trying to intercept him.

**Comment by HMBM47** [comment]
Fixed. Newest update allows you to run while trespassing, so NPCs hearing you isn't an issue anymore.

**Comment by leet-it-b** [comment]
Ok, I'm fine with that decision.
