### ISSUE TITLE
Thailand, audio bug with crew disguise

### ISSUE THREAD

**Issue by leet-it-b** [edisleado/Hitman-Bug-Tracker#57]
When you wear crew disguise, some of the NPCs react to you with phrase from "Showstopper" mission about "great working with catwalk", but there is no catwalk anywhere.

**Comment by HMBM47** [comment]
It's not just that one phrase. Everything NPCs say to you when disguised as the Sound Crew is the same things said to you when disguised as the Tech Crew from Paris, referencing the stage and (I think) lights. 
I REALLY hope these lines are placeholders, and they get into the recording studio ASAP, 'cause these lines are NOT interchangeable. Unacceptable.

**Comment by leet-it-b** [comment]
Fixed
