### ISSUE TITLE
The Sarajevo Six: The Veteran Briefing Missing

### ISSUE THREAD

**Issue by TheJadedOne** [edisleado/Hitman-Bug-Tracker#60]
Just comes up with a block of text with Diana's script.

**Comment by leet-it-b** [comment]
Should be fixed now
>Sarajevo Six Briefings [PS4 Only]
Briefings videos for The Mercenary and The Controller have been added to the game.
https://hitman.com/news/november-update-release-notes

**Comment by TheJadedOne** [comment]
Fixed long ago.
