### ISSUE TITLE
Thailand, bugged "The Smoking Gun" opportunity

### ISSUE THREAD

**Issue by leet-it-b** [edisleado/Hitman-Bug-Tracker#62]
The receptionist is completely blind, and deaf too.
https://www.youtube.com/watch?v=nMGJNI7UXZg
Also
http://www.hitmanforum.com/t/bug-report-thread/5297/1659

**Comment by HMBM47** [comment]
More issues with this opportunity:
If you run out the front door in the middle of him reading the card, he will stop reading it, then ask the receptionist again if there are any messages for him. 
video:https://youtu.be/CiiTOYhLdMk
Again, if he's in the middle of reading it and you go out of earshot within the building and come back, he will not go to the basement.
video:https://youtu.be/Nr8YdVQtIlA

**Comment by leet-it-b** [comment]
Also, if you change disguise after delivery the card, 47'll say another line to receptionist.

**Comment by leet-it-b** [comment]
Fixed
