### ISSUE TITLE
Bangkok | Jackie Carrington's double underwear

### ISSUE THREAD

**Issue by leet-it-b** [edisleado/Hitman-Bug-Tracker#78]
It's a bit weird, but it's a still a bug, you know 
![20160827184005_1](https://cloud.githubusercontent.com/assets/20925661/18028908/ec73ac4e-6c91-11e6-9f26-93515f2758cf.jpg)

**Comment by HMBM47** [comment]
Fixed
![jackiefix](https://cloud.githubusercontent.com/assets/20890580/18876176/7fdd7ee4-847d-11e6-8bcb-a51f815abf9b.jpg)
