### ISSUE TITLE
Missing lockpick icon not consistent with actual lockpick icon

### ISSUE THREAD

**Issue by edisleado** [edisleado/Hitman-Bug-Tracker#8]
Missing lockpick icon:
![20160422163814_1](https://cloud.githubusercontent.com/assets/18752617/17463568/6d1bddaa-5c96-11e6-898a-a8c81c2d6a0c.jpg)

Actual lockpick icon:
![20160507200801_1](https://cloud.githubusercontent.com/assets/18752617/17463572/7d013468-5c96-11e6-8a07-58c0b5d92123.jpg)

**Comment by edisleado** [comment]
Notified that this will be fixed in the next patch.

Source: http://www.hitmanforum.com/t/hitman-2016-unofficial-github-bug-tracker/9745/8?u=edisleado

**Comment by leet-it-b** [comment]
Still not fixed

**Comment by HMBM47** [comment]
I personally like the spanned out lock pick in the missing Pick Lock menu. I think it was a good design decision to have the spanned out version in the big menu, and made it smaller for the on screen icon. 
Although, they DID say they would "fix" this, so who knows what their plan is/was...

**Comment by wachsmuth** [comment]
This has now been fixed.

![20160929133558_1](https://cloud.githubusercontent.com/assets/9452728/18952419/c160c89e-8649-11e6-9a8c-8f0a229be267.jpg)
