### ISSUE TITLE
Marrakesh - Pushing Matthieu Mendola into canal makes documents disappear

### ISSUE THREAD

**Issue by wachsmuth** [edisleado/Hitman-Bug-Tracker#84]
It is possible to push Mendola into both the wells and the canal, either by using one of the 'follow me' opportunities, or by using distractions and emetic poison cleverly. The wells seem to work as intended - Mendola falls in, and the documents 'appear' at the side of the well, ready to be picked up.

However, if pushing him into the canal (in front of the consulate, very close to the starting location), the documents follow along and end up at the bottom of canal, impossible. You don't lose, but the mission becomes impossible to complete. If saving and loading with the documents in the canal, they disappear entirely.

**Comment by wachsmuth** [comment]
This also needs A House Built on Sand tag. Feel free to delete this comment when done :)

**Comment by leet-it-b** [comment]
Fixed?
> Fixed an issue that would cause the documents to be lost when using the 'push' prompt on Matthieu Mendola in 'A House Built on Sand'.
https://hitman.com/news/november-update-release-notes

**Comment by wachsmuth** [comment]
Has indeed been fixed, just tested to make sure. Closing.
