### ISSUE TITLE
Cherry Blossom challenge does not unlock if safe blown open

### ISSUE THREAD

**Issue by wachsmuth** [edisleado/Hitman-Bug-Tracker#87]
The Cherry Blossom challenge (unlock Claus Hugo Strandberg's safe) apparently only unlocks if it is opened by the combination, not if blown open with an explosion. This _might_ be working as intended, I am not sure.

Presumably this also applies to all other challenges that involve opening a safe.

**Comment by Morten-IOI** [comment]
Not an issue. Working as expected.

**Comment by wachsmuth** [comment]
Not a bug
