### ISSUE TITLE
Paris: Issue with trespassing while dressed in Chef disguise

### ISSUE THREAD

**Issue by HMBM47** [edisleado/Hitman-Bug-Tracker#90]
While disguised as a chef, 47 will be told he is trespassing by guards posted at the entrance of certain areas on the first floor, that should otherwise be freely accessible. This happens only when going INTO certain areas. After walking a short distance past most of these guards the GUI will no longer show 47 as trespassing and the guards don't pursue him. On the other hand, the two that lead backstage will result in combat if you run past them.
The areas in question are the North parking lot, the cafe, the museum, the dressing room, and the area just outside the dressing room.
I also noted that the trespassing area on the NE part of the map doesn't have a visible indicator of trespassing, but the guard still tells 47 he needs to leave.
All affected areas are highlighted in red below:
![trespassingchef_01](https://cloud.githubusercontent.com/assets/20890580/18810177/7cba214e-8244-11e6-94f4-9b6ab19d4ea9.jpg)

**Comment by leet-it-b** [comment]
> Fixed an issue with trespassing whilst dressed as a Chef in Paris
https://hitman.com/en-us/updates/november-update-release-notes
