### ISSUE TITLE
Colorado: Only some parts of the haybale rope can be shot to drop the haybale

### ISSUE THREAD

**Issue by wachsmuth** [edisleado/Hitman-Bug-Tracker#96]
![20160929001456_1](https://cloud.githubusercontent.com/assets/9452728/18936480/f61c3706-85e7-11e6-857c-a58bd15c1fd1.jpg)

It seems pretty weird that only the outdoor parts, and not the indoor part shown on this picture, can be shot to drop the haybale. Since shooting it indoors is much harder than outdoors, it would not be unbalancing. Right now it's just confusing that it doesn't work.

**Comment by leet-it-b** [comment]
> Fixed an issue where the hay bale in Colorado would not drop when shot in certain places
https://hitman.com/en-us/updates/november-update-release-notes

**Comment by wachsmuth** [comment]
Fixed
